"""Modèles de données."""

from .schemas import (
    ContainerStatus,
    HealthStatus,
    VmStatus,
    OsType,
    PortMapping,
    VolumeMount,
    NetworkConnection,
    ContainerInfo,
    NetworkInfo,
    TailscaleInfo,
    HostInfo,
    AgentReport,
    HostResponse,
    ContainerResponse,
    ConnectionResponse,
    GraphNode,
    GraphEdge,
    GraphData,
    # Dashboard
    NodePosition,
    DashboardNodeResponse,
    EdgeFilters,
    DashboardCreate,
    DashboardUpdate,
    DashboardResponse,
    DashboardWithPositions,
    SavePositionsRequest,
    # VM Management
    VmCreate,
    VmUpdate,
    VmResponse,
    # Agent Actions
    AgentDeployRequest,
    AgentActionRequest,
    AgentLogsRequest,
    AgentLogsResponse,
    SshTestRequest,
    SshTestResponse,
    # Container Logs
    ContainerLogEntry,
    ContainerLogsResponse,
    ContainerLogReport,
)

__all__ = [
    "ContainerStatus",
    "HealthStatus",
    "VmStatus",
    "OsType",
    "PortMapping",
    "VolumeMount",
    "NetworkConnection",
    "ContainerInfo",
    "NetworkInfo",
    "TailscaleInfo",
    "HostInfo",
    "AgentReport",
    "HostResponse",
    "ContainerResponse",
    "ConnectionResponse",
    "GraphNode",
    "GraphEdge",
    "GraphData",
    # Dashboard
    "NodePosition",
    "DashboardNodeResponse",
    "EdgeFilters",
    "DashboardCreate",
    "DashboardUpdate",
    "DashboardResponse",
    "DashboardWithPositions",
    "SavePositionsRequest",
    # VM Management
    "VmCreate",
    "VmUpdate",
    "VmResponse",
    # Agent Actions
    "AgentDeployRequest",
    "AgentActionRequest",
    "AgentLogsRequest",
    "AgentLogsResponse",
    "SshTestRequest",
    "SshTestResponse",
    # Container Logs
    "ContainerLogEntry",
    "ContainerLogsResponse",
    "ContainerLogReport",
]
